TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g 

# object files

OBJS=   main.o extra_iar.o strlen.o printf.o
OBJS+=stm32f2xx_gpio.o stm32f2xx_rcc.o startup_stm32f2xx.o  system_stm32f2xx.o 
#OBJS+= stm32f2xx_adc.o  stm32f2xx_usart.o  stm32f2xx_flash.o stm32f2xx_rtc.o   stm32f2xx_spi.o stm32f2xx_tim.o stm32f2xx_dma.o stm32f2xx_exti.o stm32f2xx_pwr.o stm32f2xx_rng.o stm32f2xx_cryp.o stm32f2xx_crc.o stm32f2xx_sdio.o stm32f2xx_syscfg.o stm32f2xx_i2c.o misc.o

# include common make file

include $(TEMPLATEROOT)/Makefile.common


