@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM 


"D:\Program Files (x86)\IAR630\common\bin\cspybat" "D:\Program Files (x86)\IAR630\arm\bin\armproc.dll" "D:\Program Files (x86)\IAR630\arm\bin\armstlink.dll"  %1 --plugin "D:\Program Files (x86)\IAR630\arm\bin\armbat.dll" --flash_loader "D:\Program Files (x86)\IAR630\arm\config\flashloader\ST\FlashSTM32F2xxxx.board" --backend -B "--endian=little" "--cpu=Cortex-M3" "--fpu=None" "-p" "D:\Program Files (x86)\IAR630\arm\CONFIG\debugger\ST\iostm32f217xx.ddf" "--semihosting" "--device=STM32F217xx" "--stlink_reset_strategy=0,0" "--drv_swo_clock_setup=72000000,0,2000000" 


